<div class="wrapper h-screen w-screen flex justify-center text-gray-700 items-center">
    <div class="flex flex-col justify-center items-center bg-white rounded-2xl shadow-2xl p-3">
        <span class="text-4xl font-black text-green-600 my-2"><span class="text-indigo-600">Singi</span>-fy</span>
        <p class="w-72 text-center text-gray-600">connect to your account with spotify to add update or create amazing playlists on the spot.</p>
        <p class="text-lg my-2">Login via <span>Spotify</span></p>
        <a href="<?php echo $link; ?>">
            <button class="hover:ring-2 ring-green-200 ring-offset-2 bg-green-700 text-white px-3 py-2 shadow-md rounded-full"><i class="fa fa-lock"></i> Connect</button>
        </a>
    </div>
</div>