<div class="login flex flex-col p-3 rounded-lg shadow bg-white  items-center justify-center">
    <ion-icon name="headset" class="text-6xl drop-shadow-lg mb-3"></ion-icon>
    <p class="text-xl font-medium">Connect your Account Now</p>
    <p class="text-center text-sm w-64">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Animi, sunt?
    </p>
    <a href="<?php echo $link; ?>">
        <button class="bg-gradient-to-r from-green-700 to-cyan-800 mt-3 focus:ring-2 focus:ring-offset-2 focus:ring-green-500 text-white px-3 py-1 rounded-full shadow-lg">
            Connect
        </button>
    </a>
</div>