<div class="grid grid-cols-12 h-screen">
    <div class="sidebar flex flex-col divide-y divide-green-100 h-screen lg:col-span-3 xl:col-span-3 md:col-span-4 sm:col-span-12 bg-white shadow-lg">
        <div class="logo text-4xl flex items-center p-3">
            <ion-icon name="diamond" class="text-green-600 drop-shadow-lg"></ion-icon>
            <p class="text-2xl ml-3 font-medium">Poti-fy</p>
        </div>
        <div class="profile p-3 flex items-center">
            <img src="https://source.unsplash.com/70x70/?avatar" class="rounded-lg shadow-lg" alt="">
            <div class="ml-3 grow capitalize">
                <p class="text-lg capitalize">Hello <?php echo $profile["display_name"] ?></p>
                <p class="text-sm text-gray-500">you have <?php echo count($userPlaylists["items"]) ?> playlists.</p>
            </div>
            <a href="/index/create">
                <button class="h-8 w-8 bg-green-500 text-white flex items-center justify-center rounded-lg shadow-lg hover:ring-2 hover:ring-offset-2 hover:ring-green-500">
                    <ion-icon name="add"></ion-icon>
                </button>
            </a>
        </div>
        <?php
        if (isset($userPlaylists)) {
            foreach ($userPlaylists["items"] as $pl) {
        ?>
                <div data="<?php echo $pl["id"] ?>" class="tile pl hover:bg-gray-200 cursor-pointer flex p-3 capitalize items-center">
                    <img src="<?php echo isset($pl["images"][0]['url']) ? $pl["images"][0]['url'] : "https://source.unsplash.com/50x50/?cool" ?>" width="50" height="50" class="rounded-lg shadow-lg" alt="">
                    <div class="grow ml-3">
                        <p class="font-medium"><?php echo $pl["name"] ?></p>
                        <p class="text-sm text-gray-700"><?php echo $pl["description"] ?></p>
                    </div>
                    <div class="expand border flex items-center p-1 rounded-lg hover:ring-2 hover:ring-green-500">
                        <ion-icon name="chevron-forward" data="<?php echo $pl["external_urls"]["spotify"] ?>" class=""></ion-icon>
                    </div>
                </div>
        <?php
            }
        }
        ?>
        <div class="grow">
        </div>
        <div class="icons p-3 flex items-center justify-between text-center">
            <p>Log out <a href="/auth/logout"><span class="text-green-600">here</span></a></p>
            <ion-icon name="play" class="hidden cursor-pointer open-player text-green-500"></ion-icon>
        </div>
    </div>
    <div class="main h-screen flex flex-col col-span-9 lg:col-span-9 xl:col-span-9 md:col-span-8 sm:col-span-12">
        <form action="#" method="post">
            <div class="search flex p-3">
                <input type="text" name="query" class="p-3 shadow grow border-0 rounded-l-lg focus:ring-0" placeholder="search here.." required>
                <button type="submit" class="shadow text-white bg-green-600 open-filter flex items-center focus:ring-2 focus:ring-offset-2 focus:ring-green-500 px-2">
                    <ion-icon name="filter"></ion-icon>
                </button>
                <button type="submit" class="shadow text-white bg-green-500 rounded-r-lg focus:ring-2 focus:ring-offset-2 focus:ring-green-500 px-2">Search</button>
            </div>
            <div class="filter hidden bg-white shadow rounded-lg p-3 flex flex-col m-3">
                <div class="flex items-center">
                    <ion-icon name="filter" class="text-green-500 text-2xl"></ion-icon>
                    <p class="ml-1">Filters</p>
                </div>
                <div class="filters p-3 flex items-center justify-around text-gray-700 text-sm">
                    <label for="album" class="flex items-center">
                        <input type="checkbox" class="border-green-500 border-2 appearence-none rounded-sm checked:bg-green-500" name="album" id="">
                        <p class="text-md ml-2">Album</p>
                    </label>
                    <label for="album" class="flex items-center">
                        <input type="checkbox" class="border-green-500 border-2 appearence-none rounded-sm checked:bg-green-500" name="artist" id="">
                        <p class="text-md ml-2">Artist</p>
                    </label>
                    <label for="album" class="flex items-center">
                        <input type="checkbox" class="border-green-500 border-2 appearence-none rounded-sm checked:bg-green-500" name="playlist" id="">
                        <p class="text-md ml-2">Playlist</p>
                    </label>
                    <label for="album" class="flex items-center">
                        <input type="checkbox" class="border-green-500 border-2 appearence-none rounded-sm checked:bg-green-500" name="track" id="" checked>
                        <p class="text-md ml-2">Track</p>
                    </label>
                    <label for="show" class="flex items-center">
                        <input type="checkbox" class="border-green-500 border-2 appearence-none rounded-sm checked:bg-green-500" name="show" id="">
                        <p class="text-md ml-2">Show</p>
                    </label>
                    <label for="episode" class="flex items-center">
                        <input type="checkbox" class="border-green-500 border-2 appearence-none rounded-sm checked:bg-green-500" name="episode" id="">
                        <p class="text-md ml-2">Episode</p>
                    </label>
                </div>
            </div>
        </form>
        <div class="chips flex px-3 py-1">
            <?php
            if (isset($search)) {
            ?>
                <div class="chip flex shadow-lg items-center bg-white rounded-full px-1 py-1/2">
                    <p class="text-sm text-gray-700 mr-1 capitalize pl-1"><?php echo $search; ?></p>
                    <a href="/index/" class="flex items-center">
                        <ion-icon name="close-circle" class="drop-shadow-lg cursor-pointer hover:text-green-900 text-2xl text-green-500"></ion-icon>
                    </a>
                </div>
            <?php
            }
            ?>
        </div>
        <div class="tabs flex bg-white mx-3 mt-2 rounded-lg">
            <div class="tab p-3 flex items-center text-green-700">
                <ion-icon name="chevron-forward"></ion-icon>
            </div>
            <?php
            $ctr = 1;
            if (isset($tabs))
                foreach ($tabs as $tab) {
            ?>
                <div class="tab capitalize text-gray-800 p-3 <?php echo $ctr == 1 ? "border-b-2" : "" ?> cursor-pointer border-green-500">
                    <p><?php echo $tab; ?></p>
                </div>
            <?php
                    $ctr++;
                }
            ?>
        </div>
        <?php
        if (isset($searchData)) {
        ?>
            <div class="sections grow bg-white m-3 rounded-lg p-3 overflow-auto grid grid-cols-12 gap-4">
                <?php
                foreach (array_keys($searchData) as $filter) {
                ?>
                    <?php
                    foreach ($searchData[$filter]["items"] as $album) {
                    ?>
                        <div class="card lg:col-span-3 md:col-span-6 sm:col-span-4 border rounded-lg p-3 shadow-lg">
                            <img src="<?php echo isset($album["images"][1]["url"]) ? $album["images"][1]["url"] : $album["album"]["images"][0]["url"] ?>" style="width: 250px;height:200px;" class="rounded-lg shadow" alt="">
                            <p class="text-xl mt-2"><?php echo strlen($album["name"]) < 19 ? $album["name"] : substr($album["name"], 0, 18) . "." ?></p>
                            <p class="text-xs text-gray-700">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis,
                                rerum.</p>
                            <button data="<?php echo $album["uri"] ?>" class="addtopl block mx-auto bg-green-500 text-white w-full p-2 rounded-lg m-3 flex items-center justify-center hover:ring-2 hover:ring-offset-2 hover:ring-green-500">Add
                                to PlayList <ion-icon class="ml-1 text-xl" name="add-circle"></ion-icon></button>
                        </div>
                    <?php
                    }
                    ?>
                <?php
                }
                ?>
            </div>
        <?php
        } else {
        ?>
            <div class="sections grow bg-white m-3 rounded-lg p-3 overflow-auto grid grid-cols-12 gap-4">

                <?php
                foreach ($recomandations["tracks"] as $album) {
                ?>
                    <div class="card lg:col-span-3 md:col-span-6 sm:col-span-4 border rounded-lg p-3 shadow-lg">
                        <img src="<?php echo isset($album["album"]["images"][1]["url"]) ? $album["album"]["images"][1]["url"] : $album["album"]["images"][0]["url"] ?>" style="width: 250px;height:200px;" class="rounded-lg shadow" alt="">
                        <p class="text-xl mt-2"><?php echo strlen($album["album"]["name"]) < 19 ? $album["album"]["name"] : substr($album["name"], 0, 18) . "." ?></p>
                        <p class="text-xs text-gray-700">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis,
                            rerum.</p>
                        <button data="<?php echo $album["album"]["uri"] ?>" class="addtopl block mx-auto bg-green-500 text-white w-full p-2 rounded-lg m-3 flex items-center justify-center hover:ring-2 hover:ring-offset-2 hover:ring-green-500">Add
                            to PlayList <ion-icon class="ml-1 text-xl" name="add-circle"></ion-icon></button>
                    </div>
                <?php
                }
                ?>
            </div>
        <?php
        }
        ?>
    </div>
</div>
<!-- if device is currently playing  -->
<?php
if (isset($device)) {
?>
    <div class="fixed bottom-0 player rounded-lg shadow-xl m-5 p-3 bg-green-500 flex flex-col justify-center items-center">
        <div class="w-full flex justify-end items-center cursor-pointer">
            <ion-icon name="close-circle-outline" class="close-player text-2xl text-white hover:ring-1 hover:rounded-full hover:ring-offset-1 ring-green-400"></ion-icon>
        </div>
        <img src="<?php echo $device["item"]["album"]["images"][0]["url"] ?>" style="width: 50px;height:50px;" class="rounded-lg shadow-lg" alt="">
        <div class="details text-xs text-white flex flex-col justify-between w-full p-2">
            <p><?php echo substr($device["item"]["album"]["name"], 0, 20) . ".." ?></p>
            <p><?php echo date("i:s", $device["progress_ms"]) ?></p>
        </div>
        <div>
            <div class="w-32 bg-gray-200 rounded-lg h-2">
                <div class="bg-red-500 h-2 rounded-lg" style="width: 25%"></div>
            </div>
        </div>
        <div class="buttons flex items-center p-2 text-white">
            <ion-icon name="play-skip-back"></ion-icon>
            <ion-icon name="play" class="text-2xl play-player"></ion-icon>
            <ion-icon name="play-skip-forward"></ion-icon>
        </div>
    </div>
<?php
}
?>
<!-- notifications -->
<div class="notifications fixed bottom-0 right-0 m-5">
    <div class="noti m-2 flex">
        <div class="n-1 bg-white flex items-center w-60 bg-gradient-to-r from-green-900 to-cyan-900 rounded-l-lg text-gray-200">
            <ion-icon name="alert-circle" class="text-6xl p-1"></ion-icon>
            <p class="text-sm text-gray-300">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
        <div class="n-2 close-noti  bg-gradient-to-l from-green-900 border-l to-cyan-900 bg-rose-500 text-gray-400 hover:text-gray-300 cursor-pointer h-100 flex items-center justify-center p-3 rounded-r-lg">
            <ion-icon name="close" class=" text-2xl text-gray-200"></ion-icon>
        </div>
    </div>
</div>
<!-- modal -->
<div style="display: none;" class="modaal backdrop bg-gray-400/50 fixed top-0 bottom-0 h-screen w-screen flex items-center justify-center">
    <div class="modaal-child bg-white rounded-lg shadow-lg lg:w-1/2 md:w-3/4">
        <div class="p-3 flex justify-center items-center">
            <button type="button" class="inline-flex items-center px-4 py-2 font-semibold leading-6 text-sm shadow-lg rounded-md text-white bg-green-500 hover:bg-indigo-400 transition ease-in-out duration-150 cursor-not-allowed" disabled="">
                <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Fetching Playlist...
            </button>
        </div>
    </div>
</div>
<?php
$this->assets->outputJs();
$this->assets->outputCss();
?>